scraper_webapp/fetch_data/urls.py
from . import views

from django.conf.urls import url


urlpatterns = [
				url(r'^$', views.index, name='index'),
				url(r'^get_url/$', views.get_url, name='get_url'),
				url(r'^downloads/(?P<page_url>[\w-]+)$', views.downloads, name='downloads'),
				url(r'^downloads/download_text_files/(?P<page_url>[\w-]+)$', views.download_text_files, name='download_text_files'),
				url(r'^downloads/download_images/(?P<page_url>[\w-]+)$', views.download_images, name='download_images'),
				url(r'^downloads/download_all_files/(?P<page_url>[\w-]+)$', views.download_all_files, name='download_all_files')
				]

scraper_webapp/scraper_webapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('fetch_data.urls', namespace='fetch_data')), 
    url(r'^admin/', include(admin.site.urls)),
]

scraper_webapp/fetch_data/models.py
from django.db import models


# model class to store link of the page to be scraped, it should be filled through user 
# submission at fetch_data app....
class ScrapWebpage(models.Model):
	page_url = models.URLField()				#stores url of webpage to be scraped

# model to store data which are scraped from the specified webapage
class Webpage(models.Model):
	#name = models.CharField(max_length=50)			
	title = models.CharField(max_length=70)			#stores title of webpage
	url = models.URLField()							#Stores the URL of the webpage
	paragraphs = models.TextField()					#Stores text content of the webpage
	links = models.URLField()						#Stores different links included on the webpage
	headings = models.CharField(max_length=200)		#Used to store different headings included on the webpage
	#images = models.ImageField()

scraper_webapp/fetch_data/forms.py
from django import forms
from fetch_data.models import ScrapWebpage

class URLForm(forms.ModelForm):
	class Meta:
		model = ScrapWebpage
		fields = ['page_url']

scraper_webapp/fetch_data/views.py
import os
import json
import tempfile
import zipfile
from cStringIO import StringIO

from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.core.servers.basehttp import FileWrapper

from .forms import URLForm
from spiders import MySpider
from .models import Webpage



def index(request):	
	return  render(request, 'fetch_data/index.html', { 'form': URLForm(), })


def get_url(request):
	if request.method == 'POST' :
		form = URLForm(request.POST)
		if form.is_valid():
			form.save()
			url = form.cleaned_data['page_url']
			conf_url = change_url(url)
			
			os.system("scrapy crawl fetch_data -a start_url="+url+" -s IMAGES_STORE='files/images/"+conf_url+"'")
			
			data = json.loads(open('fetch_data_items.json').read())
			title = data['title']
			headings = data['headings']
			links = data['links']
			paragraphs = data['paragraphs']
			
			return render(request, 'fetch_data/get_url.html', { 
																'page_url':conf_url, 
																'title':title, 
																'headings':headings, 
																'links':links, 
																'paragraphs':paragraphs, 
																})

	return  HttpResponse("Form submission failed.")

	
def downloads(request, page_url):
	return render(request, 'fetch_data/downloads.html', { 'page_url' :page_url, 'os_error':False })


def generate_text_file():
	# This method generates a text file which will be provided to user
	data = json.loads(open('fetch_data_items.json').read())
	title = data['title']
	headings = data['headings']
	links = data['links']
	paragraphs = data['paragraphs']

	with open('content.txt', 'w') as f:
		f.write("Page title: \n")
		for t in title:
			try :
				f.write(t+"\n")
			except :
				pass
		
		f.write("\nPage headings: \n")
		for heading in headings:
			try :
				f.write(heading+"\n")
			except :
				pass
		
		f.write("\nParagraphs: \n")
		for para in paragraphs:
			try :
				f.write(para+"\n")
			except :
				pass
		
		i = 0
		f.write("\nLinks: \n")
		for l in links:
			i+=1
			try:
				f.write(str(i)+". "+l+"\n")	
			except :
				pass
			

	return 'content.txt'


def download_text_files(request, page_url):
	filename = generate_text_file()
	wrapper = FileWrapper(file(filename))
	response = HttpResponse(wrapper, content_type='text/plain')
	response['Content-Disposition'] = 'attachment; filename=content.txt'
	response['Content-Length'] = os.path.getsize(filename)
	
	return response


def download_images(request, page_url):
	filenames = []
	try:
		for fn in os.listdir("files/images/"+page_url+"/full/"):
			filenames.append("files/images/"+page_url+"/full/"+fn)
	except OSError:
		# if images are not scraped, then their will also failed.
		# this exception handler handles image donwload exceptions.
		return render(request, 'fetch_data/downloads.html', { 'page_url' :page_url, 'os_error':True })
 
	# Folder name in ZIP archive which contains the above files
	zip_subdir = "images"
	zip_filename = "%s.zip" % zip_subdir

	# Open StringIO to grab in-memory ZIP contents
	s = StringIO()

	# The zip compressor
	zf = zipfile.ZipFile(s, "w")

	for fpath in filenames:
	    # Calculate path for file in zip
	    fdir, fname = os.path.split(fpath)
	    zip_path = os.path.join(zip_subdir, fname)

	    # Add file, at correct path
	    zf.write(fpath, zip_path)

	# Must close zip for all contents to be written
	zf.close()

	# Grab ZIP file from in-memory, make response with correct MIME-type
	resp = HttpResponse(s.getvalue(), content_type = "application/zip")
	# ..and correct content-disposition
	resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

	return resp


def download_all_files(request, page_url):
	textfile = generate_text_file()
	zip_subdir = "images"
	zip_filename = "files.zip"

	s = StringIO()
	archive = zipfile.ZipFile(s, 'w')
	
	archive.write(textfile, textfile)

	try:
		# download full images
		imagefiles = []
		for fn in os.listdir("files/images/"+page_url+"/full/"):
			imagefiles.append("files/images/"+page_url+"/full/"+fn)
	
		for imagefile in imagefiles:
			fdir, fname = os.path.split(imagefile)
			zip_path = os.path.join(zip_subdir, fname)

			archive.write(imagefile, zip_path)

		# code to download big thumbfiles
		thumbbig = []
		for fn in os.listdir("files/images/"+page_url+"/thumbs/big/"):
			thumbbig.append("files/images/"+page_url+"/thumbs/big/"+fn)
		
		zip_subdir_thumb_big = zip_subdir + "/thumbs/big"
		for thumbfile in thumbbig:
			fdir, fname = os.path.split(thumbfile)
			zip_path = os.path.join(zip_subdir_thumb_big, fname)

			archive.write(thumbfile, zip_path)

		# code to download small thumbfiles
		thumbsmall = []
		for fn in os.listdir("files/images/"+page_url+"/thumbs/small/"):
			thumbsmall.append("files/images/"+page_url+"/thumbs/small/"+fn)
		
		zip_subdir_thumb_big = zip_subdir + "/thumbs/small"
		for thumbfile in thumbsmall:
			fdir, fname = os.path.split(thumbfile)
			zip_path = os.path.join(zip_subdir_thumb_big, fname)

			archive.write(thumbfile, zip_path)

	except OSError:
		# if images are not scraped, then their will also failed.
		# this exception handler handles image donwload exceptions.
		pass

	archive.close()
	response = HttpResponse(s.getvalue(), content_type='application/zip')
	response['Content-Disposition'] = 'attachment; filename=%s' % zip_filename

	return response


def change_url(url):
	# change the url to be replaced as directory name for storing images.
	# now files can be differentiate on the basis of this parameter
	# mapping this parameter with actual url will give proper information about file.
	url1 = url.replace("/", "_").replace(":", "_").replace(".", "_").replace("?", "_")
	return url1

scraper_webapp/fetch_data/templates/fetch_data/downloads.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" ng-app>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'fetch_data/img/ico/favicon-html5.ico' %}">
    
    <title> Scrapage | Downloads </title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'fetch_data/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'fetch_data/css/agency.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'fetch_data/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <style type="text/css">
      .navbar-default{
        padding: 10px 0px;
        background-color: #222;
      }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'fetch_data:index' %}">Scrapage</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a href="{% url 'fetch_data:index' %}"> Home </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    
    <section>
        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right">
                <div class="col-xs-12 col-sm-9">
                    <div class="row">
                        <div class="col-6 col-sm-6 col-lg-4">
                            <h2>Download text files</h2>
                            <p>Download text data like paragraphs, headings, links in a text file.</p>
                            <p>
                                <a href="{% url 'fetch_data:download_text_files' page_url %}" class="btn btn-primary" role="button"> Download </a>
                            </p>
                        </div>

                        <div class="col-6 col-sm-6 col-lg-4">
                            <h2>Download images</h2>
                            <p>Download images in a zip file.</p>
                            <p>
                                <a href="{% url 'fetch_data:download_images' page_url %}" class="btn btn-primary" role="button"> Download </a>
                            </p>
                        </div>

                        <div class="col-6 col-sm-6 col-lg-4">
                            <h2>Download everything</h2>
                            <p>Download whole data in a zip file (including text files, images, thumbnails).</p>
                            <p>
                                <a href="{% url 'fetch_data:download_all_files' page_url %}" class="btn btn-primary" role="button"> Download </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            {% if os_error %}
            <!--<div class="col-xs-12 col-sm-9">
                <p>Can't download images.</p>
            </div>-->
            <script type="text/javascript">
                alert("Can't download images");
            </script>
            {% endif %}
        </div>    
    </section>
    
	<footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Scrapage 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'fetch_data/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'fetch_data/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    
    <script src="{% static 'fetch_data/js/classie.js' %}"></script>
    
    <script src="{% static 'fetch_data/js/cbpAnimatedHeader.js' %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
	
</body>
</html>

scraper_webapp/fetch_data/templates/fetch_data/get_url.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'fetch_data/img/ico/favicon-html5.ico' %}">
    
    <title> Scrapage </title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'fetch_data/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'fetch_data/css/agency.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'fetch_data/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <style type="text/css">
      .navbar-default{
        padding: 10px 0px;
        background-color: #222;
      }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'fetch_data:index' %}">Scrapage</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a href="{% url 'fetch_data:index' %}"> Home </a>
                    </li>

                    <!--This link left, for further insertion of links.-->
                    <li>
                        <a class="page-scroll" href="{% url 'fetch_data:downloads' page_url %}">Download</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
	
	<section id="services">
		<div class="container">
			<h1>Webpage details are:</h1>
			
			<h6>Page Url:  {{ page_url }}</h6>

			<h6>Page title:  {{ title }}</h6>
			
			<h6>Page header: {{ headings }}</h6>
			
			<p>Pragraphs:</p>
				{% for paragraph in paragraphs %}
				<p> {{ paragraph }} </p>
				{% endfor %}
			
			<p>List of links:</p>
			<ul>
				{% for link in links %}
				<li> <a href="{{ link }}">{{ link }}</a> </li>
				{% endfor %}
			</ul>
		</div>
	</section>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Scrapage 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'fetch_data/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'fetch_data/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'fetch_data/js/classie.js' %}"></script>
    <script src="{% static 'fetch_data/js/cbpAnimatedHeader.js' %}"></script>
	
</body>
</html>